import {
  Home,
  History,
  Star,
  Monitor,
  Check,
  Dot,
  StopCircle,
  FolderOpen,
  Save,
  Printer,
  ChevronsLeft,
  ChevronLeft,
  ChevronRight,
  ChevronsRight,
  Undo2,
  Redo2,
  MousePointer2,
  Image,
  Hand,
  ZoomOut,
  ZoomIn,
  PanelTop,
  RotateCw,
  RotateCcw,
  Highlighter,
  Underline,
  Strikethrough,
  Type,
  PencilLine,
  Eraser,
  Square,
  Circle,
  ArrowRight,
  Search,
  Bookmark,
  Paperclip,
  LayoutGrid,
  PanelLeftClose,
  Minus,
  Bold,
  Italic,
  Palette,
  Pencil,
  X,
  Copy,
  Trash2,
  Settings,
  MessageSquare,
  FileText,
  Files,
  ScanText,
  Signature,
  ListChecks,
  Shield,
  ArrowLeftRight,
  Maximize,
  ChevronDown,
  ArrowUpRight,
  Plus
} from 'lucide-react'

const icons = {
  home: Home,
  recent: History,
  star: Star,
  computer: Monitor,
  check: Check,
  dot: Dot,
  stop: StopCircle,
  open: FolderOpen,
  save: Save,
  print: Printer,
  first: ChevronsLeft,
  previous: ChevronLeft,
  next: ChevronRight,
  last: ChevronsRight,
  undo: Undo2,
  redo: Redo2,
  select: MousePointer2,
  image: Image,
  hand: Hand,
  zoomOut: ZoomOut,
  zoomIn: ZoomIn,
  pages: PanelTop,
  rotate: RotateCw,
  rotateLeft: RotateCcw,
  highlight: Highlighter,
  underline: Underline,
  strike: Strikethrough,
  text: Type,
  draw: PencilLine,
  eraser: Eraser,
  rectangle: Square,
  ellipse: Circle,
  arrow: ArrowRight,
  search: Search,
  bookmark: Bookmark,
  attachments: Paperclip,
  thumbnails: LayoutGrid,
  pageOnly: PanelLeftClose,
  minus: Minus,
  bold: Bold,
  italic: Italic,
  palette: Palette,

  edit: Pencil,
  close: X,
  copy: Copy,
  delete: Trash2,
  settings: Settings,
  comment: MessageSquare,
  document: FileText,
  organize: Files,
  ocr: ScanText,
  sign: Signature,
  forms: ListChecks,
  protect: Shield,
  mask: Square,
  fitWidth: ArrowLeftRight,
  fitPage: Maximize,
  down: ChevronDown,
  right: ChevronRight,
  external: ArrowUpRight,
  plus: Plus
}
export type IconName = keyof typeof icons
export function Icon({ name, size = 16 }: { name: IconName; size?: number }): React.JSX.Element {
  const Vector = icons[name]
  return (
    <Vector
      size={size}
      strokeWidth={1.75}
      aria-hidden="true"
      style={{ display: 'inline-block', flexShrink: 0, verticalAlign: 'middle' }}
    />
  )
}

export function BrandLogo({ size = 28 }: { size?: number }): React.JSX.Element {
  return <img src="./brand.svg" width={size} height={size} draggable={false} alt="Re-Edit PDF" />
}
